# This is a basic workflow to help you get started with Actions

name: Updates Corona Geomap every 2 hours

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  #push:
  #  branches:
  #    - gh-pages
  # schedule:
  #  - cron: '0 */2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          ref: gh-pages
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Runs a single command using the runners shell
    - name: Runs deploy script
      env: # Or as an environment variable
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PW: ${{ secrets.SQL_PW }}
      run: chmod +x main.py | python main.py
    
    - uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Update geomap index.html
        branch: gh-pages
